version: '3.4'

services:
  oracle:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: mssqlserver
    networks:
      - backend
    ports:
      - "1433:1433"
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "itsaSECRET1!"
      MSSQL_PID: "Enterprise"
#    healthcheck:
#      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "SA", "-P", "itsaSECRET1!", "-Q", "SELECT 1"]
#      interval: 5m
#      timeout: 10s
#      retries: 10
#      start_period: 1m
networks:
  backend: